---
name: Riyadh
surname: Radhi
position: "Senior Data Associate"
address: "Iraq-Baghdad"
profilepic: "../Riyadh.jpg"
www: "www.riyadhradhi.com"
email: "riyadhradhi0@gmail.com"
linkedin: "www.linkedin.com/in/riyadh-radhi"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 015b85
aboutme: "Senior data analyst, researcher, project manager, and team leader with a focus on Business Analytics. Passionate about analyzing trends and behaviors, and providing solutions to the community. A team Leader to connect technical teams to non-technical stakeholders."
docname: Riyadh Radhi CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae',     # The CV's LaTeX Template
             'tibble',   # Data structure for tribbles
             'here',      # Relative File Paths
             'readr',     # Data Loading
             'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = here("CV_data_20March2023.R"))
```

# WORK EXPERIENCE

```{r WORK EXPERIENCE}
work |>
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )

```

# Education

```{r EDUCATION}
edu |>
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )
```

# Management Skills 

```{r Iraq Expertise}
managing_expereinces |>
  detailed_entries(
    with = area,
    what = skills
  )
```


# Soft Skills

```{r R-SKILLS}
soft_skills |>
  detailed_entries(
    with = area,
    what = Package
  )
```

# Data Analysis Skills

```{r SKILLS}
DS_skills |>
  detailed_entries(
    with = area,
    what = skills
  )
```

# Honors

```{r HONORS}
honors |>
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

