---
name: Riyadh
surname: Radhi
position: "Lead Researcher"
address: "Istanbul Turkey"
profilepic: "../Riyadh.jpg"
www: "www.riyadhradhi.com"
email: "riyadhradhi0@gmail.com"
linkedin: "www.linkedin.com/in/riyadh-radhi"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 006999
aboutme: "Experienced researcher and programmer with focus on Data Science and Business Analytics. Applying R based solutions on daily basis to solve real business problems. Team Leader to connect technical teams with business managers."
docname: Riyadh_CV
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
require(xfun)
packages <- c('vitae'     # The CV's LaTeX Template
             ,'tibble'    # Data structure for tribbles
             ,'magrittr'  # The Pipe %>%
             ,'here'      # Relative File Paths
             ,'readr'     # Data Loading
             ,'glue'      # String Manipulation
            )
xfun::pkg_attach2(packages, message = FALSE)
source(file = here("cv_data.r"))
```

# Employment

```{r EMPLOYMENT}
work %>%
  detailed_entries(
    with = title,
    what = unit,
    why = detail,
    when = glue::glue("{startMonth} {startYear} --> {endMonth} {endYear}",.na = ""),
    where = where
  )
```

# Education

```{r EDUCATION}
edu %>%
  detailed_entries(
    with = inst,
    what = degree,
    why = detail,
    when = glue::glue("{startYear} --> {endYear}",.na = ""),
    where = where
  )
```

# Skills

```{r SKILLS}
DS_skills %>%
  detailed_entries(
    with = area,
    what = skills
  )
```

# Honors

```{r HONORS}
honors %>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

